/**
 * Shared data layer for The Trailprint Atlas.
 * One fetch, one cache, and the canonical grouping/date/stats helpers that
 * every page shares. Load after config.js and before any page script.
 */

let _hikesPromise = null;

/**
 * Fetches and caches data/hikes.json. Every caller on a page shares one
 * network request and one parsed copy (including back/forward navigation).
 */
function fetchHikes() {
    if (!_hikesPromise) {
        _hikesPromise = fetch('data/hikes.json').then(response => {
            if (!response.ok) throw new Error(`Failed to load hikes.json: ${response.status}`);
            return response.json();
        });
    }
    return _hikesPromise;
}

let _trailGeometryPromise = null;

/**
 * Fetches and caches data/trails.geojson (generated by tools/build-trails.py
 * from the raw GPX archive) and indexes it by trail_id. Each entry is an
 * array of line segments in Leaflet's [lat, lng] order, ready for L.polyline.
 */
function fetchTrailGeometries() {
    if (!_trailGeometryPromise) {
        _trailGeometryPromise = fetch('data/trails.geojson').then(response => {
            if (!response.ok) throw new Error(`Failed to load trails.geojson: ${response.status}`);
            return response.json();
        }).then(geojson => {
            const byId = {};
            geojson.features.forEach(feature => {
                const segments = feature.geometry.type === 'LineString'
                    ? [feature.geometry.coordinates]
                    : feature.geometry.coordinates;
                // GeoJSON stores [lng, lat]; Leaflet wants [lat, lng].
                byId[feature.properties.trail_id] = segments.map(
                    seg => seg.map(coord => [coord[1], coord[0]])
                );
            });
            return byId;
        });
    }
    return _trailGeometryPromise;
}

/** Groups hikes by trail_name: { "Trail Name": [hike, ...] } — repeats of a trail stay together. */
function groupByTrail(hikes) {
    const groups = {};
    hikes.forEach(hike => {
        if (!groups[hike.trail_name]) groups[hike.trail_name] = [];
        groups[hike.trail_name].push(hike);
    });
    return groups;
}

/** Groups hikes that carry a trip_tag: Map("Trip Name - Mon YYYY" -> [hike, ...]). */
function groupByTrip(hikes) {
    const trips = new Map();
    hikes.forEach(hike => {
        if (!hike.trip_tag) return;
        if (!trips.has(hike.trip_tag)) trips.set(hike.trip_tag, []);
        trips.get(hike.trip_tag).push(hike);
    });
    return trips;
}

let _crewPortraitsPromise = null;

/**
 * The Trail Crew portrait registry (data/crew.json): hand-picked photos of
 * each core-crew member, keyed by name ("Will R." -> Cloudinary public ID).
 * People without an entry fall back to a landscape from a shared hike.
 */
function fetchCrewPortraits() {
    if (!_crewPortraitsPromise) {
        _crewPortraitsPromise = fetch('data/crew.json')
            .then(response => (response.ok ? response.json() : {}))
            .catch(() => ({}));
    }
    return _crewPortraitsPromise;
}

/** Groups hikes by companion: Map("First L." -> [hike, ...]). Solo hikes appear nowhere. */
function groupByCompanion(hikes) {
    const people = new Map();
    hikes.forEach(hike => {
        (hike.hiked_with || []).forEach(name => {
            if (!people.has(name)) people.set(name, []);
            people.get(name).push(hike);
        });
    });
    return people;
}

// date_completed ("YYYY-MM-DD") parses as UTC midnight, so it must always be
// read back with UTC getters — local-time getters shift hikes a day west of UTC.

/** The (UTC) year a hike happened. */
function hikeYear(hike) {
    return new Date(hike.date_completed).getUTCFullYear();
}

/** The (UTC) month index (0-11) a hike happened. */
function hikeMonth(hike) {
    return new Date(hike.date_completed).getUTCMonth();
}

/** Formats a hike date string for display, timezone-safe. */
function formatHikeDate(dateStr, options = { year: 'numeric', month: 'long', day: 'numeric' }) {
    return new Date(dateStr).toLocaleDateString('en-US', { ...options, timeZone: 'UTC' });
}

/** The numeric part of a trail_id ("tta_43" -> 43). Ids are assigned in the
 * order hikes happened, so they order same-day hikes (multi-hike trip days). */
function hikeNumber(hike) {
    return parseInt(hike.trail_id.split('_')[1], 10);
}

/**
 * THE canonical chronological comparators. Always sort hikes with these —
 * never by date alone: same-day hikes (trip days) would land in file order,
 * which is newest-first, i.e. backwards.
 */
function compareHikesChrono(a, b) {
    return (new Date(a.date_completed) - new Date(b.date_completed))
        || (hikeNumber(a) - hikeNumber(b));
}

/** Newest first; same-day hikes: latest of the day first. */
function compareHikesChronoDesc(a, b) {
    return compareHikesChrono(b, a);
}

/**
 * The canonical headline stats. Miles and elevation count EVERY hike,
 * including repeats of the same trail (Danny's Part V decision #1).
 */
/**
 * Viewpoints are logged in the Atlas but they are not hikes — a scenic stop
 * with no trail walked. Sitewide rule (decided July 2026): never count a
 * viewpoint in a "hikes" tally; either exclude it or name it a viewpoint.
 * Where a count legitimately mixes both, call them "outings".
 */
function isViewpoint(hike) {
    return hike.hike_type === 'Viewpoint';
}

/* --- Naming a summit -------------------------------------------------------
 * A peak is often not the trail that reaches it: "Waterman Mountain Loop
 * Trail" tops out on Mount Waterman. So summit records carry an explicit
 * `peak_name` (July 2026; the wizard asks for it).
 *
 * Some real summits have no named peak at all — Savage Alpine tops out on an
 * unnamed ridge. Those keep `peak_name: null`, and the rule (decided July
 * 2026) turns on what the label is DOING:
 *
 *   summitLabel() — naming the summit itself, as in the vitals slot. An
 *       unnamed high point says "High Point", never a trail name dressed up
 *       to look like a mountain.
 *   climbName()   — telling one climb from another, as in the True Ascents
 *       ridge labels. Here the trail name is the useful fallback, because the
 *       job is identification, not naming.
 *   peakName()    — the strict answer: a real mountain's name, or null.
 */
function peakName(hike) {
    return (hike && hike.summit_trail && hike.peak_name) || null;
}

function summitLabel(hike) {
    if (!hike || !hike.summit_trail) return null;
    return hike.peak_name || 'High Point';
}

function climbName(hike) {
    if (!hike) return null;
    if (hike.peak_name) return hike.peak_name;
    // The route qualifiers a mountain never carries in its own name.
    return (hike.trail_name || '')
        .replace(/ via .*/i, '')
        .replace(/:.*/, '')
        .replace(/\s*(Loop )?Trail$/i, '')
        .replace(/ Loop$/i, '')
        .trim() || (hike.trail_name || null);
}

function getAtlasStats(hikes) {
    const trueHikes = hikes.filter(h => !isViewpoint(h));
    return {
        totalHikes: trueHikes.length,
        totalViewpoints: hikes.length - trueHikes.length,
        totalUniqueTrails: Object.keys(groupByTrail(trueHikes)).length,
        totalMiles: hikes.reduce((sum, hike) => sum + (hike.miles || 0), 0),
        totalElevation: hikes.reduce((sum, hike) => sum + (hike.elevation_gain || 0), 0)
    };
}
