/**
 * Shared configuration for The Trailprint Atlas.
 * The single home for values every page needs — load this before any other Atlas script.
 */

/**
 * The year inks (July 2026, replacing the flat-UI defaults): Blaze & Signpost
 * boldness on the Compass Rose engine — Danny's chosen hybrid. Each year turns
 * the color wheel by the golden angle (137.5°), then the hue is remapped around
 * a banned band of parchment-adjacent yellows (38°–96°), so back-to-back years
 * always sit ≥115° apart and no ink can blend into the map. Saturation and
 * lightness are tuned per hue family so every ink pops on the parchment.
 * 2022 anchors on the Atlas's original blaze blue; every future year already
 * has a color waiting — no one ever picks again.
 */
function atlasYearInk(year) {
    const raw = (132.3 + 137.5 * (year - 2022)) % 360;
    const h = (96 + raw / 360 * 302) % 360;
    let s = 62, l = 44;                                  // blues
    if (h >= 96 && h < 160) { s = 56; l = 36; }          // greens: deep forest
    else if (h >= 160 && h < 200) { s = 58; l = 38; }    // teals
    else if (h >= 250 && h < 300) { s = 48; l = 45; }    // violets, calmed
    else if (h >= 300 && h < 345) { s = 54; l = 43; }    // roses, calmed
    else if (h >= 345 || h < 20) { s = 60; l = 45; }     // reds
    else if (h >= 20 && h < 38) { s = 70; l = 46; }      // blaze orange
    const f = n => {
        const k = (n + h / 30) % 12;
        const a = (s / 100) * Math.min(l / 100, 1 - l / 100);
        const c = l / 100 - a * Math.max(-1, Math.min(k - 3, 9 - k, 1));
        return Math.round(c * 255).toString(16).padStart(2, '0');
    };
    return `#${f(0)}${f(8)}${f(4)}`;
}

const ATLAS_CONFIG = {
    // --- Cloudinary (hosts all photos) ---
    CLOUDINARY_CLOUD: 'dgdniwosl',

    // --- Trail color, keyed by the year the trail was last hiked ---
    // Generated by atlasYearInk() above, first hike year through today's:
    // every page reads this map, and it grows itself each January.
    COLOR_MAP: (() => {
        const inks = {};
        for (let y = 2022; y <= new Date().getUTCFullYear(); y++) inks[String(y)] = atlasYearInk(y);
        return inks;
    })(),
    DEFAULT_COLOR: '#7f8c8d',

    // --- Map icon file (in assets/icons/) per hike type ---
    ICON_MAP: {
        "Overnight Trip": "overnight-trip-icon.png",
        "Day Trip": "day-trip-icon.png",
        "Day Hike": "day-hike-icon.png",
        "Car Camping": "car-camping-icon.png",
        "Backpacking": "backpacking-icon.png",
        "Viewpoint": "viewpoint-icon.png"
    },

    // --- Hand-drawn stamp per hike type (July 2026): fine-line SVG glyphs in
    // the engraved-atlas style, replacing the gen-1 PNG pins on the map page.
    // Values are the inner markup of a 24x24 viewBox; render via atlasStampSvg()
    // below, which wraps them in a paper-halo copy + an ink copy (the halo keeps
    // them legible over any basemap). class="d" marks finer detail strokes.
    // The two trip types carry a celestial pair from Danny's original icon set:
    // sun = home by dark, moon = slept away.
    STAMPS: {
        "Day Hike": `
            <path d="M12 2.4 C15 2.4 16.7 4.5 16.6 7.5 C16.5 9.9 15.7 12 14.3 13.4 C13 14.7 10.7 14.6 9.6 13.2 C8.5 11.7 7.7 9.5 7.7 7.2 C7.7 4.2 9.3 2.4 12 2.4 Z"/>
            <path d="M10.3 16 L13.9 16 C14.8 16 15.4 16.7 15.3 17.6 L15.1 19.3 C15 20.3 14.2 21 13.2 21 L11.1 21 C10.1 21 9.3 20.3 9.2 19.3 L9 17.6 C8.9 16.7 9.5 16 10.3 16 Z"/>
            <path class="d" d="M10.2 5.6 L13.9 5.6 M10.2 8.3 L14.2 8.3 M10.5 11 L13.7 11"/>`,
        "Day Trip": `
            <path d="M4.9 17.3 L4.5 17.3 C3.8 17.3 3.2 16.7 3.2 16 L3.2 14.9 C3.2 14.1 3.8 13.5 4.6 13.4 L7.2 13.1 L9.4 10.6 C9.8 10.1 10.4 9.9 11 9.9 L13.8 9.9 C14.5 9.9 15.1 10.2 15.5 10.8 L17.2 13.2 L18.6 13.5 C19.3 13.6 19.9 14.2 19.9 15 L19.9 16.1 C19.9 16.8 19.3 17.3 18.6 17.3 L18.2 17.3"/>
            <path d="M13.5 17.3 L9.6 17.3"/>
            <circle cx="7.2" cy="17.3" r="1.9"/>
            <circle cx="15.9" cy="17.3" r="1.9"/>
            <path class="d" d="M13.4 10.4 L13.5 13 L8.1 13"/>
            <circle class="d" cx="19.1" cy="5.4" r="1.7"/>
            <path class="d" d="M19.1 2.1 L19.1 2.9 M19.1 7.9 L19.1 8.7 M15.8 5.4 L16.6 5.4 M21.6 5.4 L22.4 5.4 M16.8 3.1 L17.4 3.7 M20.8 7.1 L21.4 7.7 M21.4 3.1 L20.8 3.7 M17.4 7.1 L16.8 7.7"/>`,
        "Overnight Trip": `
            <path d="M4.4 13 L10.8 7 L17.2 13"/>
            <path d="M6.2 11.6 L6.2 19.8 L15.4 19.8 L15.4 11.6"/>
            <path class="d" d="M9.4 19.8 L9.4 16.4 C9.4 15.6 10 15 10.8 15 C11.6 15 12.2 15.6 12.2 16.4 L12.2 19.8"/>
            <path class="d" d="M19.2 3.4 A3.1 3.1 0 1 0 21.3 8.5 A3.9 3.9 0 0 1 19.2 3.4 Z"/>`,
        "Car Camping": `
            <path d="M12 5.6 L19.8 19.3 L4.2 19.3 Z"/>
            <path class="d" d="M10.4 3.9 L12 6.2 M13.6 3.9 L12 6.2"/>
            <path class="d" d="M9.6 19.3 L12 13.8 L14.4 19.3"/>`,
        "Backpacking": `
            <path d="M6.9 6.6 C7.3 4.9 8.9 3.9 10.7 3.9 L12.9 3.9 C14.3 3.9 15.5 4.7 16 6 C17.1 8.7 17.3 12.7 16.7 15.7 C16.4 17.2 16 18.5 15.5 19.5 L9.9 19.5 C9 19.5 8.3 18.8 8.3 17.9 L8.3 7.4 Z"/>
            <path d="M8.3 8.2 C6.2 9.7 5.8 13.7 7.2 16.6"/>
            <rect class="d" x="11.5" y="12.4" width="3.5" height="4.2" rx="1.2"/>`,
        "Viewpoint": `
            <path d="M6.6 7.4 C6.6 6.2 7.3 5.4 8.2 5.4 C9.1 5.4 9.8 6.2 9.8 7.4 L9.8 9.2 L11.4 13 L11.4 16.6 C11.4 17.7 10.5 18.6 9.4 18.6 L6.6 18.6 C5.5 18.6 4.6 17.7 4.6 16.6 L4.6 13 L6.6 9.2 Z"/>
            <path d="M17.4 7.4 C17.4 6.2 16.7 5.4 15.8 5.4 C14.9 5.4 14.2 6.2 14.2 7.4 L14.2 9.2 L12.6 13 L12.6 16.6 C12.6 17.7 13.5 18.6 14.6 18.6 L17.4 18.6 C18.5 18.6 19.4 17.7 19.4 16.6 L19.4 13 L17.4 9.2 Z"/>
            <path class="d" d="M9.8 7.9 L14.2 7.9"/>
            <circle class="d" cx="12" cy="10.9" r="1.05"/>`
    },

    // --- Trail Crew: companions with at least this many shared hikes are
    // "core crew" — they get a card on crew.html and a member page ---
    CREW_CORE_MIN_HIKES: 10,

    // --- Season per UTC month index (0 = Jan ... 11 = Dec) ---
    SEASON_BY_MONTH: [
        'winter', 'winter',                       // Jan, Feb
        'spring', 'spring', 'spring',             // Mar, Apr, May
        'summer', 'summer', 'summer',             // Jun, Jul, Aug
        'autumn', 'autumn', 'autumn',             // Sep, Oct, Nov
        'winter'                                  // Dec
    ]
};

/**
 * Renders one hike-type stamp as an inline SVG string: the glyph drawn twice,
 * first as a thick paper-colored halo, then as fine ink lines on top — the
 * knockout that keeps a printed map symbol readable over any terrain. The ink
 * inherits CSS currentColor, so the surrounding element chooses the color.
 */
function atlasStampSvg(hikeType) {
    const inner = ATLAS_CONFIG.STAMPS[hikeType] || ATLAS_CONFIG.STAMPS['Day Hike'];
    return `<svg class="stamp-glyph" viewBox="0 0 24 24" aria-hidden="true"><g class="stamp-halo">${inner}</g><g class="stamp-ink">${inner}</g></svg>`;
}

/**
 * Builds a Cloudinary delivery URL for an image public ID.
 * @param {string} publicId - e.g. "tta_43-lost-palms-oasis-trail-01"
 * @param {string} transform - Cloudinary transform string, e.g. "w_800,h_600,c_fill,q_auto,f_auto"
 *
 * Every upload carries a ~30 KB embedded ICC color profile that Cloudinary
 * preserves on derived images — a 40px thumbnail was arriving at 30 KB.
 * cs_srgb converts the pixels to standard sRGB (colors stay true), and
 * fl_strip_profile then drops the profile: most photos shrink by ~30 KB,
 * roughly half their size at gallery dimensions (measured July 2026).
 */
function cloudinaryUrl(publicId, transform = 'q_auto,f_auto') {
    return `https://res.cloudinary.com/${ATLAS_CONFIG.CLOUDINARY_CLOUD}/image/upload/${transform},cs_srgb,fl_strip_profile/${publicId}`;
}

/**
 * Photo-loading machinery for the lightboxes. Full-size Cloudinary images
 * can take a couple of seconds; the answer is preloading, not placeholders
 * (a holding card was tried July 2026 and retired — every variant flickered).
 * Loaded Image objects are cached so "is it warm?" survives across flips.
 */
const _photoCache = {};
function blurUpPreload(url) {
    if (!_photoCache[url]) { const im = new Image(); im.src = url; _photoCache[url] = im; }
    return _photoCache[url];
}
/**
 * Show a photo as fast as possible:
 *  - already loaded (the common case when flipping in order, thanks to the
 *    neighbor preloads below and hover warming at the call sites) → at once;
 *  - otherwise the current frame simply holds until the new photo is ready —
 *    no placeholder states.
 * Neighbors warm only AFTER the current photo lands — they must never
 * compete with it for bandwidth. Rapid flips are token-guarded: only the
 * newest request may land.
 */
function blurUpShow(img, publicId, transform, neighborIds = []) {
    const fullUrl = cloudinaryUrl(publicId, transform);
    img.dataset.blurToken = fullUrl;
    const isWarm = im => im.complete && im.naturalWidth > 0;
    const warmNeighbors = () => neighborIds.forEach(id => blurUpPreload(cloudinaryUrl(id, transform)));

    const full = blurUpPreload(fullUrl);
    if (isWarm(full)) {
        img.src = fullUrl;
        warmNeighbors();
        return;
    }
    full.addEventListener('load', () => {
        if (img.dataset.blurToken !== fullUrl) return;   // superseded by a newer flip
        img.src = fullUrl;
        warmNeighbors();
    }, { once: true });
}
